return {
    ESPEnabled   = true,
    ShowBoxes    = true,
    ShowNames    = true,
    ShowDistance = true,
    ShowHealth   = true,
    ESPTeamCheck = true,
    AimbotEnabled= true,
    FOV          = 120,
    Smoothness   = 15,
    AimPart      = "Head",
    AimKeyType   = "key",
    AimKeyMouse  = Enum.UserInputType.MouseButton2,
    AimKeyCode   = Enum.KeyCode.E,
    AimKeyLabel  = "E",
    AimTeamCheck = true,
    KnifeEnabled = true,
    KnifeKey     = Enum.KeyCode.F,
    KnifeKeyLabel= "F",
    KillAllKey   = Enum.KeyCode.G,
    WalkSpeed    = 66,
    JumpPower    = 70,
    Noclip       = false,
    InfJump      = false,
    Godmode      = false,
}
